config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "movies#index"

  get '/explorer/search', to: 'explorer#search', as: :explorer_search

  post "/bookmarks/create", to: "bookmarks#create", as: :bookmarks_create

  resources :movies
  resources :explorer, only: [:index]
  resources :dashboards, only: [:index]
  resources :lists do
    resources :bookmarks, only: [:new, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { maximum: 550 }
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :bookmarks, dependent: :destroy
  has_one_attached :photo
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  def to_param
    tmdb_id.to_s
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :lists
  has_one_attached :photo

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    added_attrs = [:firstname, :lastname, :age, :phone_number, :description, :city, :favorite_gender, :photo]
    devise_parameter_sanitizer.permit(:sign_up, keys: added_attrs)
    devise_parameter_sanitizer.permit(:account_update, keys: added_attrs)
  end

end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_bookmark, only: :destroy

  def create
    movie = Movie.find_or_create_by(tmdb_id: params[:tmdb_id]) do |m|
      m.name = params[:title]
      m.poster_url = params[:poster_path]
    end

    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.movie = movie

    if @bookmark.save
      redirect_to list_path(@bookmark.list), notice: "Film ajouté à la liste ✅"
    else
      redirect_back fallback_location: root_path, alert: "Erreur lors de l'ajout ❌"
    end
  end

  def destroy
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:list_id, :name, :comment, :rating)
  end

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = current_user
  end

end

app/controllers/explorer_controller.rb
class ExplorerController < ApplicationController
  

  def index
    query = params.dig(:search, :query)

    if query.present?
      movies = Tmdb::MovieSearchService.new(query).fetch
    else
      movies = Tmdb::TopRatedMoviesService.new(language: 'en-US').fetch
    end

    @movies = Kaminari.paginate_array(movies).page(params[:page]).per(12)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_list, only: [:show, :destroy]

  def index
    @lists = current_user.lists
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.user = current_user
    if @list.save
      redirect_to list_path(@list), notice: "Liste créée."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @list.destroy
    redirect_to lists_path, status: :see_other
  end

  def show
    @bookmarks = @list.bookmarks.includes(:movie)
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :photo)
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :authenticate_user!, only: [:show]

  def index
    @movies = Tmdb::TopRatedMoviesService.new(language: 'en-US').fetch
    @movie_banner = Movie.all.sample
  end

  def show
    @movie_banner = Movie.find_by(tmdb_id: params[:id]) # ne lève plus d'erreur ici

    @movie = Tmdb::MovieDetailsService.new(id: params[:id], language: 'en-US').fetch

    unless @movie
      redirect_to movies_path, alert: 'Film introuvable.'
      return
    end

    @bookmark = Bookmark.new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/explorer_helper.rb
module ExplorerHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<div class="container">
  <div class="form">
    <h2>Ajoute un bookmark</h2>
    <%= simple_form_for [@list, @bookmark] do |f| %>
      <%= f.association :movie, collection: Movie.order(:title), prompt: "Choisis un film" %>
      <%= f.input :comment, label: "Votre avis" %>
      <%= f.input :photo, as: :file %>
      <%= f.submit "Enregistrer", class: "btn btn-success" %>
    <% end %>
  </div>
  <div class="btn-wrapper"><%= link_to "Retour", lists_path, class:"btn-list"%></div>
</div>

app/views/dashboards/index.html.erb
<div class="container-dashboard">

  <div class="profile-user">
    <div class="profile-left">
      <h2><%= @user.firstname %> <%= @user.lastname %></h2>
      <%= cl_image_tag @user.photo.key, class: "image-profile-dashboard" %>
    </div>

    <div class="profile-right">
      <div class="profile-right-p1">
        <p class="title-input-profile">Age</p>
        <p><%= @user.age %> ans</p>
        <p class="title-input-profile">City</p>
        <p><%= @user.city %></p>
        <p class="title-input-profile">Bio</p>
        <p class="description-profile"><%= @user.description %></p>
      </div>

      <div class="profile-right-p2">
        <p class="title-input-profile">Phone number</p>
        <p><%= @user.phone_number %></p>
        <p class="title-input-profile">Email</p>
        <p><%= @user.email %></p>
        <p class="title-input-profile">Favorite movies</p>
        <p><%= @user.favorite_gender %></p>
      </div>
    </div>
  </div>

  <div class="logout-link"><%= button_to "Déconnexion", destroy_user_session_path, method: :delete, class: "logout-button" %>
</div>

app/views/explorer/index.html.erb
<%= simple_form_for :search, url: explorer_index_path, method: :get, html: { class: 'search-form-mobile' } do |f| %>
  <div class="search-form-control form-group">
    <%= f.input :query, input_html: { class: 'form-control', placeholder: "Rechercher" }, label: false %>
    <button type="submit" class="btn-form">
      <i class="fas fa-search"></i>
    </button>
  </div>
<% end %>

<div class="movie-desktop">
  <div class="movies-cards">
    <% @movies.each do |movie| %>
      <div class="movie-card">
        <%= link_to movie_path(movie['id']) do %>
          <div class="movie-card-wrapper">
            <%= image_tag("https://image.tmdb.org/t/p/w300#{movie['poster_path']}", alt: "#{movie['title']} poster", class: "image_movie") %>
            <p class="movie-card-title"><%= movie['title'] %></p>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

<div class="carrousel-mobile-explorer">
  <section class="splide" data-controller="splide" aria-label="Top Movies Carousel">
    <div class="splide__track">
      <ul class="splide__list">
        <% @movies.each do |movie| %>
          <li class="splide__slide">
            <div class="movie-card">
              <%= link_to movie_path(movie['id']) do %>
                <div class="movie-card-wrapper">
                  <%= image_tag("https://image.tmdb.org/t/p/w300#{movie['poster_path']}", alt: "#{movie['title']} poster", class: "image_movie") %>
                  <p class="movie-card-title"><%= movie['title'] %></p>
                </div>
              <% end %>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </section>
</div>
<%= paginate @movies, class: "pagination" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Labobine</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/@splidejs/splide@4.1.4/dist/css/splide.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/@splidejs/splide@4.1.4/dist/js/splide.min.js"></script>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
      <div class="container-fluid">
        <%= link_to movies_path do %>
          <h1 class= "nav-title">Labobine<span id="point">.</span></h1>
        <% end %>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <i class="fas fa-bars" style="color: #ffffff;"></i>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto">
            <%# if user_signed_in? %>
              <li class="nav-item">
                <%= link_to "Home", movies_path, class: "nav-link" %>
                <%= link_to "Explorer", explorer_index_path, class: "nav-link" %>
                <%= link_to "Lists", lists_path, class: "nav-link" %>
                <% if user_signed_in? %>
                  <%= link_to "Profile", dashboards_path, class: "nav-link" %>
                <% else %>
                  <%= link_to "Connexion", new_user_session_path, class: "nav-link" %>
                <% end %>
              </li>
            <%# else %>
              <!--li class="nav-item"-->
                <%#= link_to "Login", new_user_session_path, class: "nav-link" %>
              <!--/li-->
            <%# end %>
          </ul>
        </div>
      </div>
    </div>





    <div class="header-container">
      <%= link_to movies_path do %>
        <h1>Labobine<span id="point">.</span></h1>
      <% end %>

      <%= simple_form_for :search, url: explorer_index_path, method: :get, html: { class: 'search-form' } do |f| %>
        <div class="search-form-control form-group">
          <%= f.input :query, input_html: { class: 'form-control', placeholder: "Rechercher" }, label: false %>
          <button type="submit" class="btn-form">
            <i class="fas fa-search"></i>
          </button>
        </div>
      <% end %>

      <div class="menu">
        <%= link_to "Home", movies_path %>
        <%= link_to "Explorer", explorer_index_path, id:"explorer-menu" %>
        <%= link_to "Lists", lists_path, id:"list-menu" %>
      </div>

      <div class="user-profile">
        <% if user_signed_in? %>
          <%= link_to dashboards_path, class: "username-btn" do %>
            <%= cl_image_tag current_user.photo.key, class: "image-profile" %>
            <%= current_user.firstname %> <%= current_user.lastname[0].upcase %>
          <% end %>
        <% else %>
          <%= link_to "Connexion", new_user_session_path, class: "connexion-btn" %>
        <% end %>
      </div>
    </div>

      <%= yield %>

    <div class="footer">
      <div class="footer-links">
        <a href="#"><i class="fab fa-github"></i></a>
        <a href="#"><i class="fab fa-instagram"></i></a>
        <a href="#"><i class="fab fa-facebook"></i></a>
        <a href="#"><i class="fab fa-twitter"></i></a>
        <a href="#"><i class="fab fa-linkedin"></i></a>
      </div>
    </div>
  </body>
</html>

app/views/lists/index.html.erb
<div class="container">
  <h1 id="list-title">Your Lists<span id="point">.</span></h1>

  <div class="movies-cards">
    <% @lists.each do |list| %>
      <div class="movie-card">
        <%= link_to list_path(list) do %>
          <div class="movie-card-wrapper">
            <% if list.photo.attached? && list.photo.key.present? %>
              <%= cl_image_tag list.photo.key,
                    alt: list.name, class: "image_movie" %>
            <% else %>
              <div class="image placeholder"></div>
            <% end %>
            <p class="movie-card-title"><%= list.name %></p>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>

  <h2 id="list-subtitle">Add a list</h2>
  <div class="btn-wrapper">
    <%= link_to "+", new_list_path, class: "btn-list" %>
  </div>
</div>

app/views/lists/new.html.erb
<div class="new-container">
  <div class="form">
    <h2>Add new list</h2>

    <%= simple_form_for @list do |f| %>
      <%= f.input :name %>
      <%= f.input :photo, as: :file %>
      <%= f.button :submit, "Save", class: "btn" %>
    <% end %>
  </div>
  <div class="btn-wrapper"><%= link_to "Back", lists_path, class:"btn-back"%></div>
</div>

app/views/lists/show.html.erb
<div class="container">
  <div class="actions-bar">
    <div class="delete-list">
        <%= link_to "Delete list",
            list_path(@list),
            data: { turbo_method: :delete, turbo_confirm: "Are you sure?" },
            class: "link-delete-list" %>
      </div>
  </div>

  <h1 class="list-name"><%= @list.name %></h1>

  <% if @bookmarks.any? %>
    <div class="movie-list">
      <% @bookmarks.each do |bookmark| %>
        <div class="movie-card-bookmark">

          <div class="card-image-bookmark">
            <% if bookmark.movie.poster_url.present? %>
              <% if bookmark.movie.poster_url.present? %>
                <%= image_tag "https://image.tmdb.org/t/p/w500#{bookmark.movie.poster_url}", class: "image-bookmark", alt: bookmark.movie.name %>
              <% end %>
            <% end %>
          </div>

          <div class="content-bookmark">
            <h3><%= bookmark.movie.name %></h3>
            <p><strong>Rating :</strong> <%= bookmark.rating %> /5</p>
            <p><strong>Comment :</strong> <%= bookmark.comment %></p>
            <%= link_to "Delete",
              list_bookmark_path(@list, bookmark),
              data: { turbo_method: :delete, turbo_confirm: "Are you sure?" },
              class: "btn-delete-bookmark" %>
          </div>
        </div>
      <% end %>
    </div>
  <% else %>
    <p>No movies in this list yet.</p>
  <% end %>

  <div class="btn-wrapper">
    <%= link_to "Back", lists_path, class: "btn-back" %>
  </div>
</div>

app/views/movies/index.html.erb
<div class="container-home">

  <!-- Desktop Banner -->

  <%= link_to movie_path(@movie_banner), class: "banner-link desktop-banner" do %>
    <div class="banner" style="background-image: url('<%= asset_path(@movie_banner.poster_url) %>')">
      <div class="banner-text">
        <h2><%= @movie_banner.name %><span id="point">.</span></h2>
        <p><%= @movie_banner.mini_description %></p>
      </div>
    </div>
  <% end %>

</div>

  <!-- Mobile Banner -->

  <div class="banner-link mobile-banner">
    <% @movies.sample(1).each do |movie| %>
      <%= link_to movie_path(movie['id']) do %>
        <div class="banner-mobile-img" style="background-image: url('https://image.tmdb.org/t/p/w300<%= movie['poster_path'] %>');">
          <div class="banner-text">
            <h2><%= movie['title'] %><span id="point">.</span></h2>
            <p><%= truncate(movie["overview"], length: 70) %></p>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>



<div class="container-home">

  <div class="movie-desktop">
    <h3>You may like</h3>
    <div class="movies-cards">
      <% @movies.sample(5).each do |movie| %>
        <div class="movie-card">
          <%= link_to movie_path(movie['id']) do %>
            <div class="movie-card-wrapper">
              <%= image_tag("https://image.tmdb.org/t/p/w300#{movie['poster_path']}", alt: "#{movie['title']} poster", class: "image_movie") %>
              <p class="movie-card-title"><%= movie['title'] %></p>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="carrousel-mobile">
    <h3>You may like</h3>
    <section class="splide" data-controller="splide" aria-label="Top Movies Carousel">
      <div class="splide__track">
        <ul class="splide__list">
          <% @movies.sample(5).each do |movie| %>
            <li class="splide__slide">
              <div class="movie-card">
                <%= link_to movie_path(movie['id']) do %>
                  <div class="movie-card-wrapper">
                    <%= image_tag("https://image.tmdb.org/t/p/w300#{movie['poster_path']}", alt: "#{movie['title']} poster", class: "image_movie") %>
                    <p class="movie-card-title"><%= movie['title'] %></p>
                  </div>
                <% end %>
              </div>
            </li>
          <% end %>
        </ul>
      </div>
    </section>
  </div>

</div>


<%# <script>
  document.addEventListener( 'DOMContentLoaded', function() {
    var splide = new Splide( '.splide', {
    type   : 'loop',
    padding: '5rem',
    gap: '20px',
  } );

  splide.mount();
  } );
</script> %>

app/views/movies/show.html.erb
<div class="container">
  <div class="content">
    <% if @movie['poster_path'] %>
      <%= image_tag "https://image.tmdb.org/t/p/w500#{@movie['poster_path']}", class:"image-description"%>
    <% end %>
    <div class="content-text">
      <h1><%= @movie['title'] %></h1>
      <p><%= @movie['overview'] %></p>
        <%= simple_form_for @bookmark, url: bookmarks_create_path do |f| %>
          <%= hidden_field_tag :tmdb_id, @movie["id"] %>
          <%= hidden_field_tag :title, @movie["title"] %>
          <%= hidden_field_tag :poster_path, @movie["poster_path"] %>
          <%= hidden_field_tag :overview, @movie["overview"] %>

          <%= f.input :list_id, collection: current_user.lists, label: "Choose your list" %>
          <%= f.input :rating, label: "Rating on 5", input_html: { min: 1, max: 5, step: 1 }, as: :integer %>
          <%= f.input :comment, label: "Your comment" %>

          <%= f.submit "Add to list", class: "btn" %>
        <% end %>
      </div>
    </div>


  </div>
</div>